### ISSUE TITLE
Some tables are malformed

### ISSUE THREAD

**Issue by Kupoman** [panda3d/panda3d-docs#10]
There are 13 malformed tables:
* source/panda3d-docs/source/programming-with-panda3d/advanced-operations-with-internal-structures/how-panda3d-stores-vertices-and-geometry/geomvertexdata.rst:51
* source/panda3d-docs/source/programming-with-panda3d/advanced-operations-with-internal-structures/procedural-generation/creating-the-geomprimitive-objects.rst:134
* source/panda3d-docs/source/programming-with-panda3d/collision-detection/collision-entries.rst:25
* source/panda3d-docs/source/programming-with-panda3d/collision-detection/collision-entries.rst:41
* source/panda3d-docs/source/programming-with-panda3d/panda3d-rendering-process/creating-windows-and-buffers.rst:60
* source/panda3d-docs/source/programming-with-panda3d/panda3d-rendering-process/the-graphics-pipe.rst:52
* source/panda3d-docs/source/programming-with-panda3d/render-to-texture-and-image-postprocessing/dynamic-cube-maps.rst:33
* source/panda3d-docs/source/programming-with-panda3d/render-to-texture-and-image-postprocessing/dynamic-cube-maps.rst:43
* source/panda3d-docs/source/programming-with-panda3d/texturing/automatic-texture-coordinates.rst:34
* source/panda3d-docs/source/programming-with-panda3d/texturing/texture-combine-modes.rst:309
* source/panda3d-docs/source/programming-with-panda3d/texturing/texture-wrap-modes.rst:51
* source/panda3d-docs/source/programming-with-panda3d/the-scene-graph/searching-the-scene-graph.rst:59
* source/panda3d-docs/source/programming-with-panda3d/the-scene-graph/searching-the-scene-graph.rst:96

**Comment by rdb** [comment]
Fixed in 82dfce93e58f2c8306f06b6ea719881d9a0ac261 and 50e1931325f018324eb1da83078c611b724bfde9.
