### ISSUE TITLE
Document makeTextureBuffer's behaviour when the buffer size is 0,0

### ISSUE THREAD

**Issue by Germanunkol** [panda3d/panda3d-docs#100]
When calling `base.win.makeTextureBuffer` with a size of 0,0, then it looks like subsequent resizes of the main window will also modify the size of the created texture buffer.

If this is intended behaviour (is it?) it would be nice if it was documented.

I expected to find this information here: https://docs.panda3d.org/1.10/python/reference/panda3d.core.GraphicsOutput?highlight=maketexturebuffer#panda3d.core.GraphicsOutput.makeTextureBuffer

**Comment by rdb** [comment]
I suspect this is intended, but should indeed be documented.
