### ISSUE TITLE
Method-names in search displayed as numbers

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d-docs#114]
It seems that, when searching the API, methods are labelled not with their names, but with numbers. That is, in place of "panda3d.core.NodePath.setPos", the listing might have "panda3d.core.NodePath.12". (Or some other number.)

See for example this search for "clockObject":
(Deselected "Search contents of pages" for a clearer depiction of the issue.)
https://docs.panda3d.org/1.10/python/search?q=clockobject&check_keywords=yes&area=default

![Screenshot from 2021-12-07 11-31-13](https://user-images.githubusercontent.com/36933600/145003536-fc2dde98-6331-48aa-8900-79f002f87124.png)

**Comment by serkkz** [comment]
It may be strange, but I've never seen anything like it
![1](https://user-images.githubusercontent.com/17797036/145083677-a3cd9d95-916c-43a3-a08c-64848f7e2c27.png)
.

**Comment by rdb** [comment]
I think it's fixed now. You may need to clear your cache.

**Comment by ArsThaumaturgis** [comment]
Ah, much better--I can confirm that it appears to be fixed! Thank you for that! ^_^
