### ISSUE TITLE
Scroll bar for side menu

### ISSUE THREAD

**Issue by afefafafe** [panda3d/panda3d-docs#126]
Based on this post https://discourse.panda3d.org/t/panda3d-docs-page-lacks-a-scrollbar/29069 it would be nice to have a scroll bar for the side menu. It can be rather painful to navigate the API section of the docs without one. 

![image](https://user-images.githubusercontent.com/54505044/212774002-d50aece3-b5d3-4414-b810-0a74494cb5f3.png)

**Comment by rdb** [comment]
Should be fixed now.  But I'm not sure we should have all the individual classes on the left side, better to just go back via the index page, or use the search function.
