### ISSUE TITLE
Reformat everything to match coding style

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d-docs#18]
I propose that we adopt Python's style guide as a starting point for our own:
https://devguide.python.org/documenting/#style-guide

I am proposing:
* Running text (not tables or code) is wrapped to a 80-character ruler
* Indentation is 3 spaces (except for code, which is indented to the base indent of the code block plus 4 spaces per level for Python and 2 spaces per level for C++)
* No three (four?) consecutive newlines
* No whitespace at end of line
* Single newline at end of file

I've gone ahead and checked in an [.editorconfig file](https://github.com/panda3d/panda3d-docs/blob/master/.editorconfig) to codify some of this.  However, a lot of pages don't yet obey this, using inconsistent indentation, and either wrapped to a 78-character ruler, what appears to be an 82-character ruler, or not at all.

We should create a script to fix the indentation, and then use CI to enforce the correct style.

**Comment by Moguri** [comment]
I took a quick skim over the style guide and didn't see it, but I would say that each sentence should be on a new line as this makes merging easier.

I never really did understand the 3 space indent that is common for rst. I am fine with following it just so we can point to an existing style guide like this, but it seems like 2 or 4 would be better and more consistent with our source code.

**Comment by rdb** [comment]
The 3-space indent does make indenting Python and C++ code under code blocks a bit more awkward (since it requires mixing two indentation styles), but I would still slightly lean towards it due to the fact that it is an established style guideline, used by Python as well, and the directive syntax used by Sphinx looks designed for it (the directive name nicely lines up with the content with 3 spaces).

Note that 2-space won't exactly work as many places require at least 3 spaces.

I am happy to be overruled on this if others lean towards 4-space, but if we want to change we should probably decide it now to save us the effort of needing to reformat everything again.

**Comment by Moguri** [comment]
I'm okay with sticking to 3.

**Comment by rdb** [comment]
I gone ahead and added a note to the coding style saying that long code examples should be stored in a separate .py file and referenced using a `.. literalinclude::` directive.  This largely solves the issue of mixed indentation, and makes automated testing and linting of those code samples easier.

**Comment by rdb** [comment]
I think this is more-or-less done now, primarily in 6c6afd1f873c6f8351ac455ab091d464f2ce3374.
