### ISSUE TITLE
Get docs hosted on panda3d.org

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d-docs#2]
I am not sure if this step has been done. However, we should get this new manual hosted in a staging area on panda3d.org and put a link in this repo's README.

**Comment by treamology** [comment]
There's a link to the RTD version in the README. Do we know if we want to keep it there or host it on our own server?

**Comment by Moguri** [comment]
@rdb expressed a desire to self-host. I do not care a whole lot either way, but we need to get a location picked and sorted out.

**Comment by rdb** [comment]
I will work on this shortly—can we take down links to the RTD version ASAP so that it doesn't start getting indexed?

**Comment by treamology** [comment]
Done.

**Comment by rdb** [comment]
I have uploaded a version to panda3d.org; I'm going to continue to use #3 to track the automatic uploading of new versions.
