### ISSUE TITLE
Display warning banner for outdated releases

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d-docs#25]
We could use this extension to warn people if they're browsing a version of the documentation that is no longer supported.
https://sphinx-version-warning.readthedocs.io/en/latest/

**Comment by Moguri** [comment]
Does this extension work when not hosting on RTD? Looks like it makes use of the RTD api.

**Comment by rdb** [comment]
Possibly not; I did not look deeply into this.  I guess we can otherwise just look at how the extension adds the banner and replicate this.

**Comment by rdb** [comment]
I have now added a dynamically added banner using code that fetches version info from a `_versions.json` file above the HTML root; this allows us to change the version metadata without rebuilding all of the older versions of the documentation.
