### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d-docs#3]
If we haven't already, we should setup continuous deployment for this manual. I'm guessing will setup something with buildbot.panda3d.org.

**Comment by rdb** [comment]
I think we can use GitHub Actions for building new versions and uploading them to the panda3d.org server.

**Comment by rdb** [comment]
I've set up a variety of automated tests/lints and a workflow that automatically builds and uploads the documentation to `https://www.panda3d.org/docs/{branch}/`.
