### ISSUE TITLE
Sample Programs links to "Texture Swapping" which was never added to Panda3D.

### ISSUE THREAD

**Issue by denmarkx** [panda3d/panda3d-docs#37]
Link: [Sample Programs: Texture Swapping](https://docs.panda3d.org/1.10/python/more-resources/samples/texture-swapping#texture-swapping). 

Commit [78c3593](https://github.com/panda3d/panda3d/tree/78c3593d2cde39218a8a087be7abec9cdfe6f812/samples) in the Panda3D repository added all the sample programs into the repository, but texture swapping is no where to be found.

**Comment by denmarkx** [comment]
I found the texture swapping sample program in an earlier version of Panda3D. 1.6.2 to be exact. I'm not sure if you'd like a pull request to be made to put this program in the main repository, if you're planning to delete the page entirely, or something else.

**Comment by rdb** [comment]
Thanks, I've removed references to this sample from the manual.
