### ISSUE TITLE
usage of cleanup with actors unclear

### ISSUE THREAD

**Issue by BMaxV** [panda3d/panda3d-docs#40]
Hello,

there is a warning upon removing nodes for actors that just removing them without calling cleanup() is bad?

I have no idea what that does though I would expect it to go here:

https://docs.panda3d.org/1.10/python/programming/models-and-actors/loading-actors-and-animations

And the docstring is also empty so the API doesn't help either:

https://docs.panda3d.org/1.10/python/reference/direct.actor.Actor.html?highlight=cleanup#direct.actor.Actor.Actor.cleanup

**Comment by rdb** [comment]
Thanks, I've added an explanation of this to both the API reference and the manual.

**Comment by BMaxV** [comment]
Thanks for doing this so quickly!
