### ISSUE TITLE
Links in search results don't work.

### ISSUE THREAD

**Issue by janEntikan** [panda3d/panda3d-docs#42]
None of the links in search results seem to work.

Steps to reproduce:
1. Search for something
2. Click on a result

**Comment by ArsThaumaturgis** [comment]
I just ran into this, too.

Specifically, it looks like the links produced by searches lack the "python"/"cpp" part of the URL. So, for example, the URL for the API entry on the "CollisionSphere" class looks like this:

```https://docs.panda3d.org/1.10/python/reference/panda3d.core.CollisionSphere```

While the URL returned by a search looks like this (omitting highlighting, etc.):

```https://docs.panda3d.org/1.10/reference/panda3d.core.CollisionSphere.html```

Note the lack of "python/" between "1.10/" and "reference/".

Link to a search that--for me, at least--produces such a broken result:
https://docs.panda3d.org/1.10/python/search?q=collisionsphere&check_keywords=yes&area=default

(This seems to hold true for both API and manual URLs.)

**Comment by rdb** [comment]
This is caused by an update in Sphinx, namely sphinx-doc/sphinx#7192, which changes search results to use absolute URLs instead of relative.

I think until this is changed back upstream, we'll just have to ship our own copy of searchtools.js.
