### ISSUE TITLE
Update Windows screenshots in introductory chapter for Windows 10

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d-docs#48]
The Windows screenshots in the introductory section look dated, because they were made with Windows 7, and Panda3D 1.8.  We should redo them on Windows 10.

**Comment by treamology** [comment]
Maybe this issue should be extended to any outdated-looking screenshots. For example, the section on debugging Panda on Windows contains screenshots made with the Windows XP silver theme.

**Comment by anushkrishnav** [comment]
Can I work on it ?

**Comment by rdb** [comment]
Yes, please go ahead.
