### ISSUE TITLE
Setup version selection 

### ISSUE THREAD

**Issue by Moguri** [panda3d/panda3d-docs#5]
The manual should be versioned and follow Panda's versioning. In other words, a user should be able to see a version of the manual that is specific to the version of Panda they are using. We probably don't separate manual versions for each patch release.

I know ReadTheDocs can do this, so there are likely extensions to handle this. However, we'll need to look into how the multiple versions are handled and what we need to do to support them with our CI/CD.

**Comment by treamology** [comment]
RTD handles manual versioning on its own when hosting with them (either through branches or tags, I forget). We'll have to come up with something ourselves if we do our own hosting.

**Comment by treamology** [comment]
[Since we've decided to do our own hosting](https://github.com/panda3d/panda3d-docs/issues/2#issuecomment-528804896), this seems to be the most-used option when it comes to self-hosted versioning: https://github.com/sphinx-contrib/sphinxcontrib-versioning

**Comment by rdb** [comment]
It's also possible to just host a ReadTheDocs instance.  However, I will investigate the versioning plug-in.

**Comment by rdb** [comment]
Apparently sphinxcontrib-versioning does not work with the latest Sphinx version and is not being maintained.

I am not sure we gain much from using such an extension anyway; we could just build each version to a different directory and add a selector to the theme.

**Comment by rdb** [comment]
Going to close this as versioning exists (even if it's just in a minimal form); having new versions uploaded automatically can be tracked by #3.  If there more actionable items regarding versioning, we can reopen and add them to this issue, or open a new issue.
