### ISSUE TITLE
Linking problem on Panda3d website

### ISSUE THREAD

**Issue by Shadow2121** [panda3d/panda3d-docs#90]
If we click on any button in navigation bar except HOME button from Community page of the PANDA3D  website it is showing the page not fount Error.

**Comment by rdb** [comment]
Looks like an issue that was introduced by updating Discourse.

**Comment by Shadow2121** [comment]
should I just mention it in panda3d-web?

**Comment by rdb** [comment]
Nah, we don't really have an issue tracker for the Discourse system… let's just leave it here for now, I'll see if I can take care of it.

**Comment by rdb** [comment]
OK, that was easy.  It's fixed now, thanks for reporting.
