### ISSUE TITLE
Typo in method description

### ISSUE THREAD

**Issue by granitdula** [panda3d/panda3d-docs#96]
For the `__isub__` dunder method in the `LMatrix4f` class, there seems to be a typo in its description. It says "Performs a memberwise addition between two matrices." when it should say "Performs a memberwise subtraction between two matrices." Here is the link: [https://docs.panda3d.org/1.10/python/reference/panda3d.core.LMatrix4f#panda3d.core.LMatrix4f.__isub__](https://docs.panda3d.org/1.10/python/reference/panda3d.core.LMatrix4f#panda3d.core.LMatrix4f.__isub__)

**Comment by rdb** [comment]
Thanks, pushed a fix to the docstring, this will be updated at the next release.
